name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_DATABASE: ${{ secrets.DB_NAME }}
          MYSQL_ALLOW_EMPTY_PASSWORD: true
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping --silent" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

#      - name: Wait for MySQL to be ready
#        run: |
#          until mysqladmin ping -h localhost; do
#            echo "Waiting for MySQL..."
#            sleep 10
#          done

      - name: Execute Initialization Script
        run: |
          mysql --host=localhost --user=root --password="" --protocol=TCP ${{ secrets.DB_NAME }} < init_db.sql

      - name: Set up database environment
        run: |
          echo "DB_HOST=${{ secrets.DB_HOST }}" >> .env
          echo "DB_USER=${{ secrets.DB_USER }}" >> .env
          echo "DB_PASSWORD=" >> .env
          echo "DB_NAME=${{ secrets.DB_NAME }}" >> .env

      - name: Start application
        run: node search.js &

      - name: Run tests
        run: npm test
